### PR TITLE
Ed 876 global sports content

### PR DESCRIPTION
**Pull request by robfinchtrade**
Have finally - FINALLY - finished uploading images and text to this.

### CODE REVIEW

**Comment by richtier** [comment]
@robfinchtrade tests are failing. I will fix them

**Comment by richtier** [comment]
@robfinchtrade tests fixed. this is what the page looks like:

image

some things of note:
 - there is no hero image in the banner. I suspect there should be?
 - there are only two companies. should there be

**Comment by robfinchtrade** [comment]
@richtier The "third company" should be this box
image
Not sure how to get that in there.
Re: the hero image, can you point me to where in the code I need to add it?

**Comment by richtier** [comment]
[this is the file](https://github.com/uktrade/directory-ui-supplier/blob/ED-876-global-sports-content/enrolment/templates/marketing-pages/sports-infrastructure.html)

the edit that file and the changes will be reflected in this pull request.

I will update the template to make the blue box show.

**Comment by richtier** [comment]
@robfinchtrade this is what the page looks like 
image

**Pull request merged**
